modLoader="javafml" #mandatory
loaderVersion="[46,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="followme"
version="1.1.8"
displayName="Follow Me"
displayURL="https://www.curseforge.com/minecraft/mc-mods/follow-me"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/follow-me/1.20/update.json"
credits="bstylia14 for the original mod concept and for providing ideas during development."
authors="Smileycorp"
description="Allows a configurable list of entities to follow the player after a shift right-click."

[[dependencies.followme]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.9,)"
    ordering="NONE"
    side="BOTH"