modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="followme"
version="1.1.6"
displayName="Follow Me"
displayURL="https://www.curseforge.com/minecraft/mc-mods/follow-me"
updateJSONURL="https://raw.githubusercontent.com/SmileycorpMC/follow-me/1.17/update.json"
credits="Smileycorp"
authors="bstylia14 for the original mod concept and for providing ideas during development."
description="Allows a configurable list of entities to follow the player after a shift right-click."

[[dependencies.followme]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.3,)"
    ordering="NONE"
    side="BOTH"